workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    environment:
      flutter: stable
      java: 17
      vars:
        PACKAGE_NAME: "com.pro.speedy"
        KEYSTORE_BASE64: "<YOUR_BASE64_KEYSTORE>" # Set this in Codemagic Environment variables (secure)
        KEYSTORE_PASSWORD: "Star234"            # Secure
        KEY_ALIAS: "key"                         # Can be non-secure
        KEY_PASSWORD: "Star234"                  # Secure
    pre_build:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Decode Keystore
        script: |
          mkdir -p android/app
          echo $KEYSTORE_BASE64 | base64 --decode > android/app/upload-keystore.jks
    build:
      - name: Build Signed Release AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=1
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your_email@example.com
