workflows:
  android-build:
    name: Android Build
    max_build_duration: 120
    environment:
      flutter: stable
      java: 17
      vars:
        PACKAGE_NAME: "com.pro.speedy"
        KEYSTORE_BASE64: "<YOUR_BASE64_KEYSTORE>" # Codemagic Secrets me set karein
        KEYSTORE_PASSWORD: "Star234"
        KEY_ALIAS: "key"
        KEY_PASSWORD: "Star234"

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get

      - name: Decode keystore and write key.properties
        script: |
          mkdir -p android/app
          echo "$KEYSTORE_BASE64" | tr -d '\r\n' | base64 --decode > android/app/keystore.jks
          echo "storeFile=keystore.jks" > android/key.properties
          echo "storePassword=$KEYSTORE_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "✅ Keystore and key.properties created"

      - name: Build Signed Release AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=1

    artifacts:
      - build/app/outputs/bundle/release/*.aab
