workflows:
  android-build:
    name: Android Release Build
    max_build_duration: 120
    environment:
      flutter: stable
      java: 17
      vars:
        PACKAGE_NAME: "com.pro.speedy"
        KEYSTORE_PASSWORD: "Star234"
        KEY_ALIAS: "key"
        KEY_PASSWORD: "Star234"
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get

      - name: Decode Keystore
        script: |
          echo "$KEYSTORE_BASE64" | base64 --decode > $CM_BUILD_DIR/android/app/keystore.jks

      - name: Build Signed Release AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=1

    artifacts:
      - build/app/outputs/bundle/release/*.aab
