name: speedy_cricket
description: A simple cricket bowling speed measurement app.
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

development_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
